lavenderdotpet/LibreQuake

lq1/maps/make.sh, lq1/maps/src-compile/buildconfigs/start.conf
- Add support for map-specific compiler options via `buildconfigs/MAP.conf`.
- Improved help script to provide more detail and provide a version number.
- Add `QBSP_FLAGS`, `LIGHT_FLAGS`, and `VIS_FLAGS` flags for overriding map-specific options, globally.
- Add `QBSP_PATH`, `LIGHT_PATH`, and `VIS_PATH` for specifying locations other than `$PATH` for ericw-tools.
- Check for ericw-tools before trying to compile maps.
- Map compilation will now supress non-warnings, and print out the currently worked on map.
- General cleanup and performance improvements.
=> Add improved make.sh map building script.

qcsrc/localization.qc, qcsrc/lq1/cutscene_camera.qc, qcsrc/progs.src, qcsrc/weapons.qc
Adds the following new impulse commands:
`200` - Spawns a cutscene camera. Maximum of three can be at play. 
`201` - Increments the automatic-switching delay by five seconds. 
`202` - Decrements the automatic-switching delay by five seconds. 
`203` - Begins 'playback' of demo cameras.
`developer 1` must be enabled before use, otherwise `bprint`s are fired reporting you to turn the cvar on.
https://github.com/MissLavender-LQ/LibreQuake/assets/26030250/ea476937-7c80-480a-a751-3e247371402a
=> QC: Add SVC_CUTSCENE-based cameras for use in demo recording

build.py, qcsrc/client.qc, qcsrc/combat.qc, qcsrc/defs.qc, qcsrc/doors.qc, qcsrc/monsters/fiend.qc, qcsrc/monsters/ogre.qc, qcsrc/monsters/rottweiler.qc, qcsrc/monsters/shub.qc, qcsrc/monsters/spawn.qc, qcsrc/monsters/vore.qc, qcsrc/plats.qc, qcsrc/progs.src, qcsrc/subs.qc, qcsrc/triggers.qc, qcsrc/weapons.qc
Fixes behaviors when non-clients interact with `trigger_teleport` via `.use` causing execution of `__NULL__`. Also replaces all references of the `SUB_Null `-> `__NULL__` macro with `__NULL__` outright, suggested to mitigate confusion.
Also opts into building with `-O3`, verified that optimizations only cause issues when compiling mutators, which LibreQuake is not.
=> QC: Fix call to `__NULL__` in `teleport_use`, move away from `SUB_Null` macro

texture-wads/compile_wads.py
build.py calls compile_wads.py - and that one needs to also compile the new lq_palette.wad
=> compile_wads.py: Add missing lq_palette

.flake8, .github/workflows/linting.yml, .gitignore, bin/py/asset_analyze.py, bin/py/quake16x.py, build.py, lq1/maps/compile_maps.py, texture-wads/compile_wads.py
This change adds a tiny CI workflow to keep the python files clean.
I made the initial changes to the py files which mostly was inconsistent whitespaces and some minor issues.
The pipelines runs only on pull requests at moment and in the future could be expanded to check that your usual release build workflows runs without issues.
PS: I have excluded docs/.etherpad-backups from the checks since I assume this is an unmaintained file.
Also since github actions haven't been configured for this repository before the CI run won't be triggered due to security but should run on the next PR.
=> Add a minimal CI workflow

.github/workflows/python_checks.yml
I figured it makes more sense to run this check on pushes containing changes in python files instead of any old PR
=> Change ci trigger from PR to push

qcsrc/client.qc, qcsrc/localized_text.qc
Uses data structures to improve implementation for adding new epilogues to specific maps via QuakeC, as well as allows the developer to specify which CD Track to use. Demonstrates usefulness by 1-lining support for LibreQuake's Episode 0, which fixes #117.
=> QC: Enhance Intermission+Epilogue Implementation, Add Episode 0 Epilogue.

lq1/dev.cfg
] = game speed up
[ = game speed down
' = game speed reset
https://github.com/MissLavender-LQ/LibreQuake/assets/51702517/8e6c721f-f34f-4dc1-a853-6405757ed7b4
=> new host_timescale dev binds

.github/scripts/install_deps.sh, .github/workflows/build_release.yml, build.py, lq1/maps/compile_maps.py, texture-wads/compile_wads.py
This adds a github ci workflow to build the release artifacts.
- The full release build takes roughly 50min
- On every push to `main` a full release is built so we can be sure everything works once we do decide to create a release
- When there are several pushes to master only the latest will have a running pipeline. Redundant pipelines will be canceled
- When a release is created (via the website) the pipeline will be launched and full release will be built. Additionally the assets will then be uploaded to the release page. They will appear at the usual place once the pipeline completes.
- The release build python script used to spam a lot of text which I had to reduce. This way we can better see what happens and when errors occur.
=> Add a release build workflow

.github/scripts/install_deps.sh, .github/workflows/build_release.yml, lq1/maps/compile_maps.py
This makes the build release pipeline run in parallel. There are separate jobs for the steps and the matrix strategy is used where possible.
The runtime is drastically reduced (~50min to ~10min) and since artifacts need to be passed from job to job they can be downloaded from the actions summary page as well.
- Dependencies now get installed to `/usr/local/bin` which is in `$PATH` and therefore we can skip the PATH setup
- Created seperate steps for building progs, wads and maps and all is assembled in the end
- Updated some of the actions to newer versions to get rid of deprecation warnings
- Added a change to `compile_maps.py` to enable us to build only maps in a specific directory and thats how I seperated out the build_maps jobs
=> Make release build ci run in parallel

docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.desktop, docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.metainfo.xml
The reviewer in our flatpak submission PR (https://github.com/flathub/flathub/pull/5530) said that these files are supposed to live in the repository here instead of the flatpak pull request.
=> Add flatpak metadata

lq1/maps/compile_maps.py
This change makes a map compile fail if there are textures missing.
I have tested this on the faulty commit in [!173](https://github.com/lavenderdotpet/LibreQuake/pull/173) and it worked
---
=> BUILD: Fail map compile on missing textures

qcsrc/client.qc
---
During the qwprogs.dat merge, I missed this bit of code that needs to be removed in the `qwprogs.dat`. If this is not removed, the player is unable to jump out of liquids in QW. This is especially problematic in lqdm4, where the player is unable to escape the lava if they fall in.
---
---
=> QC: Fixed being unable to climb out of water in QW

.github/workflows/build_release.yml
fteqcc nees glibc version 2.38 at minimum. This might be a recent update who knows. However the Ubuntu-latest tag seems to also pick runners using Ubuntu 22.04 which is too old and doesn't satisfy the libc dependency. I set this manually to 24.04 but this should be reverted at some point. Actually it should work right now. This feels like a GitHub bug. They have 24.04 runners available but latest points to something older.
---
=> CI: Fix fteqcc failure due to outdated glibc version in github runners

docs/deathmatch-setup-guide.txt, qcsrc/deathmatch_settings.qc, qcsrc/player.qc
---
I've always disliked the backpack mechanic in Quake 1 deathmatch. In duels, it punishes the out-of-control player for picking up ammo since often it will do little more than deliver the in-control player free ammo. I've added an infokey that lets you disable it. They're still enabled by default, of course.
---
=> QC, DOCS: Added infokey for disabling backpacks in deathmatch

lq1/default.cfg, lq1/default_$generic.cfg
---
improved controller support + doom style weapon switch as an optional toggle in the config keyboard and a default for controller on the dpad
also turned cl_alwaysrun to 1 which is "quakespasm" which means u press shift to slow walk
---
https://github.com/user-attachments/assets/20662cf4-276a-44bc-a40e-986cdd21f694
---
=> CFG: controller binds, doom style weapon switch and config changes

build_components.json
---
well widle1.wav can't be build because widle1.wav doesn't exist in build_components.json
so I fixed it!
this Pull Request solve this problem. 
---
=> AUDIO: Update build_components.json for Wizard sound fix

.github/workflows/build_release.yml, build.py, build_components.json
---
- Fixed qwprogs.dat not ending up in GitHub built releases.
- Made 'missing asset with no replacement' a build-failing error rather than just a warning. (So we can make sure this doesn't happen again.)
- Removed missing assets from build_components.json.
---
=> BUILD: Fixed qwprogs.dat not being put into GitHub built releases.

lq1/default_fte.cfg
---
Removed FTEQW's hacky and buggy anti-zfighting feature. This was useful for the original game since a lot of the original game's maps had zfighting. Ideally, our maps shouldn't have any zfighting so this setting is unnecessary. This fix was causing problems for a couple of our maps including e2m5 and e1m4.
Fixes the e2m5 issue in this ticket: https://github.com/lavenderdotpet/LibreQuake/issues/162
---
---
=> CONFIG: Disabled hacky zfighting fix in FTEQW

docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.desktop, docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.launcher.desktop, docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.launcher.sh, docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.sh
---
This adds right-click options on the .desktop file for directly launching new engines and opening the user content directory, as well as a secondary .desktop file to run the launcher after it has saved the engine selection. Prerequisite for https://github.com/flathub/io.github.lavenderdotpet.LibreQuake/pull/7.
---
=> [BUILD] Add launcher for additional engines in Flatpak

.github/workflows/build_release.yml, .gitignore, build_components.json, build_releases.json, lq1/default.cfg, lq1/server_config.cfg, qcsrc/world.qc
---
- Added a new release that contains content for a QuakeWorld server. This includes the DM maps, the singleplayer maps (with the 'lq_' prefix added to prevent filename collisions with the levels from the original game), the qwprogs.dat, and a starting server config. All maps are unpacked to make it possible to download the maps.
- Made our custom qwprogs.dat enable low gravity for `lq_e1m8.bsp`. This fix will only work for servers running our custom qwprogs.dat, but this is unfortunately the best solution I can think of.
- Added a server_config.cfg which contains suggested default settings for a LibreQuake server.
---
=> BUILD: Added a release containing the content needed to set up a QW server

docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.sh
---
This fixes the issue where the "open user content directory" button in the GUI launcher for the Flatpak isn't working.
[launcher.webm](https://github.com/user-attachments/assets/f6ae201b-821b-4d27-85e8-d1f2530cff48)
---
=> BUILD: Fix user content directory button in launcher

docs/flatpak-metadata/io.github.lavenderdotpet.LibreQuake.sh
---
As per https://github.com/flathub/io.github.lavenderdotpet.LibreQuake/pull/7, this flips the default engine for LibreQuake to Ironwail from Quakespasm.
---
=> BUILD: Switch default engine in Flatpak launcher to Ironwail

build_components.json
---
fixed dhit2 being mislabeled as dhit in the build script thus preventing the file from being used in the game
dhit2 being a sound for the moonrat/demon 
---
---
=> BUILD: fixed dhit2.wav being mislabled as dhit.wav

.github/scripts/install_deps.sh
---
This change switches qpakman to the main branch of LibreQuake's qpakman repo (https://github.com/LibreQuake/qpakman), which contains some updates with regards to mipmap generation and performance.
---
The new qpakman version has slightly more detailed mipmaps, due to featuring a new downscaling algorithm, but the changes are subtle.
---
=> CI: Switch to LibreQuake's qpakman
